

spring:
  data:
    mongodb:
      uri:
      database: ${MONGODB_URI}
      auto-index-creation: true
  main:
    allow-circular-references: true

server:
  port: ${ SEVER_PORT }
  servlet:
    context-path: /unholy-dev