spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: journaldb
      auto-index-creation: true
  main:
    allow-circular-references: true

server:
  port: ${SEVER_PORT}
  servlet:
    context-path: /unholy-prod